print('=====DESAFIO 02=====')
print('Crie um scrpt Python que leia o dia, mês e ano de nascimento de uma pessoa e mostre a data formatada.')
dia = input('Que dia você nasceu? ')
mes = input('Que mês você nasceu? ')
ano = input('Que ano você nasceu? ')
print('Você nasceu no dia ', dia, ' de ', mes, ' de ', ano, '. Correto?')
