print('=====DESAFIO 03=====')
print('Crie um script Pyhton que leia dois números e tente mostrar a soma entre eles')
n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))
print (f'A soma entre {n1} e {n2} é {n1 + n2}.')
